import { DM_Sans } from "next/font/google";
import "@/styles/base.scss";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Preloader from "@/components/Preloader";
import { PopupsProvider } from "@/context/PopupsContext";
import OrderPopup from "@/components/OrderPopup";
import RequestPopup from "@/components/RequestPopup";

const dmsans = DM_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Next Wave Ad",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={dmsans.className}>
        <PopupsProvider>
          <Preloader />
          <Header />
          <main className="site">{children}</main>
          <Footer />
          <OrderPopup />
          <RequestPopup />
        </PopupsProvider>
      </body>
    </html>
  );
}
